version: "3.7"

services:
  database:
    image: postgres
    container_name: database_chatdesck
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=chatdesck
      - POSTGRES_PASSWORD=chatdesck
      - POSTGRES_DB=chatdesck
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: chatdesck
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
